apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-python-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-python-backend
    spec:
      containers:
        - name: python-fastapi
          image: pravinnpci/npci-forum-python-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-python-backend
